language: rust
sudo: false
matrix:
  include:
    - rust:
      - stable
      - nightly
      install:
        - npm i
        - rustup component add rustfmt-preview
      cache: cargo
      script:
        - cargo test
        - cargo run --example major_libs --release
        - cargo +nightly fmt --all -- --check
notifications:
  email: never