language: rust
sudo: false
matrix:
  include:
    - rust: stable
      install:
        - npm i
        - rustup toolchain install nightly
        - rustup component add rustfmt-preview --toolchain nightly
      cache:
        - cargo: true
        - directories:
          - node_modules
      script:
        - cargo test
        - cargo run --example major_libs --release
        - cargo +nightly fmt --all -- --check
      after_script:
        - git add proptest-regressions
        - git commit -m "proptest-regressions update [ci skip]"
      stages:
        after_script:
          - if branch in (master, next)
notifications:
  email: never