[package]
name = "ress"
version = "0.1.1"
authors = ["Robert Masen <r@robertmasen.pizza>"]
description = "A sanner/tokenizer for JS files"
keywords = ["JavaScript", "parsing", "JS", "ES", "ECMA"]
categories = ["parsing", "text-processing", "web-programming"]
license = "MIT"
repository = "https://github.com/freemasen/ress"
readme = "./README.md"

[badges]
travis-ci = { repository = "FreeMasen/RESS", branch = "master" }

[dependencies]
combine = "3.3"

[dev-dependencies]
reqwest = "0.8"
docopt = "0.9"
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`

[[example]]
name = "major_libs"
path = "examples/major_libs/src/main.rs"

[[example]]
name = "clear-comments"
path = "examples/clear-comments/src/main.rs"